name: instagram_clone_app
description: Flutter app, which clone some Instagram features.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^2.17.0
  firebase_auth: ^4.11.0
  firebase_storage: ^11.3.0
  cloud_firestore: ^4.10.0
  uuid: ^4.1.0
  hooks_riverpod: ^2.3.8
  font_awesome_flutter: ^10.4.0
  flutter_facebook_auth: ^5.0.11
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  image: ^4.1.3
  flutter_hooks: 0.18.6
  collection: ^1.17.0
  intl: ^0.18.1
  video_thumbnail: ^0.5.3
  video_player: ^2.7.2
  lottie: ^2.3.2
  share_plus: ^7.2.1
  url_launcher: ^6.1.11
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/animations/empty.json
    - assets/animations/loading.json
    - assets/animations/data_not_found.json
    - assets/animations/error.json
    - assets/animations/small_error.json
